#include "hardwareSpecific.h"



_FOSCSEL(FNOSC_FRCPLL & IESO_OFF);
_FBS(RBS_NO_RAM & BSS_NO_FLASH & BWRP_WRPROTECT_OFF);
_FSS(RSS_NO_RAM & SSS_NO_FLASH & SWRP_WRPROTECT_OFF);
_FPOR(FPWRT_PWR64);
_FOSC(FCKSM_CSECME & OSCIOFNC_ON & IOL1WAY_OFF & POSCMD_NONE);
_FWDT( FWDTEN_OFF );
_FICD( ICS_PGD3 & JTAGEN_OFF);

