echo off
SET EXTENSION=.elf
SET PRJNAME=%1
SET FILENAME=%PRJNAME%%EXTENSION%
SET PREFIX=noComment
SET NEWNAME=%PREFIX%%FILENAME%

SET TOOLCHAIN=arm-none-eabi
SET SIZE= %TOOLCHAIN%-size
SET STRIP= %TOOLCHAIN%-strip
SET OBJCOPY= %TOOLCHAIN%-objcopy

copy %FILENAME% %NEWNAME%

REM %STRIP% -R=.common %NEWNAME%

%OBJCOPY% -O ihex %FILENAME%  %PRJNAME%.hex
%SIZE% %FILENAME%